SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY,
SUM (A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK A JOIN AUTHOR B JOIN BOOK_SALES C
WHERE B.AUTHOR_ID = A.AUTHOR_ID
AND A.BOOK_ID = C.BOOK_ID
AND C.SALES_DATE like '2022-01-%'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;