-- 상품코드 별 매출액 합계를 출력 (판매가 * 판매량) -> 매출액 기준 내림차순, 상품코드 오름차순
-- OFFLINE 테이블에서 제품 별 묶어서 SLAES_AMOUNT의 합계를 구해서 사용
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) * A.PRICE AS SALES
FROM PRODUCT AS A
JOIN OFFLINE_SALE AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID
ORDER BY SUM(SALES_AMOUNT) * A.PRICE DESC, PRODUCT_CODE;