-- 코드를 입력하세요
WITH L AS (
    SELECT A.ANIMAL_ID, A.NAME, A.DATETIME - B.DATETIME AS TIME
    FROM ANIMAL_OUTS AS A
    JOIN ANIMAL_INS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    ORDER BY A.DATETIME - B.DATETIME DESC
    LIMIT 2
)

SELECT ANIMAL_ID, NAME
FROM L;