-- 입양 간 기록은 있지만, 보호소 들어온 기록이 없는 동물
-- ID, 이름 을 ID 순으로 조회

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS AS A
LEFT JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NULL
ORDER BY A.ANIMAL_ID;