-- 입양 기록은 존재하는데, 보호소 들어온 기록이 없는 동물의 ID와 이름을 조회.
WITH ID_LIST AS (
    SELECT A.ANIMAL_ID AS INS_ID, B.ANIMAL_ID AS OUTS_ID, A.NAME
    FROM ANIMAL_OUTS AS A
    LEFT JOIN ANIMAL_INS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.ANIMAL_ID IS NULL
    )

SELECT INS_ID AS ANIMAL_ID, NAME
FROM ID_LIST
ORDER BY ANIMAL_ID;
# SELECT * FROM ID_LIST;