-- 잡은 물고기의 종류 별 마리 수와 , 물고기 이름 출력
SELECT COUNT(A.ID) AS FISH_COUNT, B.FISH_NAME
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME
ORDER BY COUNT(A.ID) DESC;