-- [2021년에 가입 회원 중 상품 구매한 회원 / 2021년에 가입한 전체 회원]
-- 년, 월별로 출력

WITH U AS (
    SELECT COUNT(USER_ID)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR, 
      MONTH(SALES_DATE) AS MONTH,
      COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
      ROUND(COUNT(DISTINCT USER_ID) / (SELECT * FROM U), 1) AS PUCHASED_RATIO
      FROM ONLINE_SALE
      WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021)
      GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
      ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE);