-- [2021년에 가입한 회원 중 상품을 구매한 회원수] / [2021년에 가입한 전체 회원 수]
-- 년, 월 별로 출력 -> 년, 월 그룹 묶기
-- 년 월 별로 상품을 구매한 회원 수 
WITH TOTAL_2021 AS (
    SELECT COUNT(USER_ID) AS TOTAL_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT * FROM TOTAL_2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS A
JOIN USER_INFO AS B
ON A.USER_ID = B.USER_ID
WHERE YEAR(B.JOINED) = 2021
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE);