-- 아직 입양을 못 간 동물 중, [가장 오래 보호소에 있었던 동물 3마리]의 [이름]과 [보호 시작일] 조회.
-- 가장 오래면 [DATETIME 이 MIN]
-- 입양을 못 감 -> ANIMAL_OUTS 의 DATETIME 이 NULL;

WITH A_LIST AS (
    SELECT A.ANIMAL_ID AS ANIMAL_ID, A.NAME AS NAME, A.DATETIME AS INS_DATE, B.DATETIME AS OUTS_DATE
    FROM ANIMAL_INS AS A
    LEFT JOIN ANIMAL_OUTS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.DATETIME IS NULL
    ORDER BY A.DATETIME
)
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
JOIN A_LIST AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATETIME
LIMIT 3;

# SELECT * 
# FROM ANIMAL_OUTS
# WHERE NAME = "Rocky";