-- 생산일자가 [2022년 5월인 식품들] 의 [식품ID], [식품 이름], [총매출]

WITH FOOD_GROUP AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT 
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
)

SELECT A.PRODUCT_ID, PRODUCT_NAME, (B.AMOUNT * A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
JOIN FOOD_GROUP AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY B.AMOUNT * A.PRICE DESC, A.PRODUCT_ID;