-- 7월 테이블과 , 상반기 테이블의 TOTAL_ORDER 을 더해서 FLAVOR 를 기준으로 가장 높은 3개만 출력
-- 각 테이블마다 FLAVOR 로 GROUP BY 해야할듯

WITH JULY_FLAVOR AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
), RESULT AS (
    SELECT A.FLAVOR AS FLAVOR, (A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF AS A
    JOIN JULY_FLAVOR AS B
    ON A.FLAVOR = B.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)

SELECT FLAVOR
FROM RESULT
LIMIT 3;
