-- [보호 시작일]보다 [입양일]이 빠른 동물의 아이디와 이름을 조회.
-- 보호 시작일 -> ANIMAL_INS 의 DATETIME
-- 입양일     -> ANIMAL_OUTS 의 DATETIME

WITH ID_LIST AS (
    SELECT A.ANIMAL_ID AS ANIMAL_ID, A.NAME AS NAME, A.DATETIME AS INS_DATE, B.DATETIME AS OUTS_DATE
    FROM ANIMAL_INS AS A
    JOIN ANIMAL_OUTS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE A.DATETIME > B.DATETIME
    ORDER BY A.DATETIME
)

SELECT ANIMAL_ID, NAME
FROM ID_LIST;