WITH S AS (
    SELECT EMP_NO, SUM(SCORE) AS RESULT_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT S.RESULT_SCORE AS SCORE, S.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM S
JOIN HR_EMPLOYEES AS B
ON S.EMP_NO = B.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;