WITH AVG_SAL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT AVG_SAL.DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM AVG_SAL
JOIN HR_DEPARTMENT
ON AVG_SAL.DEPT_ID = HR_DEPARTMENT.DEPT_ID
ORDER BY AVG_SAL DESC;