-- 부서별 평균 연봉을 조회! 부서별로 [부서ID] [영문 부서명] [평균 연봉] 
WITH AVG_SAL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT A.DEPT_ID, A.DEPT_NAME_EN, B.AVG_SAL
FROM HR_DEPARTMENT AS A
JOIN AVG_SAL AS B
ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_ID
ORDER BY AVG_SAL DESC;