-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름 조회
WITH MAX_PRODUCT AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT B.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A
JOIN MAX_PRODUCT AS B
ON A.CATEGORY = B.CATEGORY
AND A.PRICE = B.MAX_PRICE
HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;