WITH FISH AS (
    SELECT ID, 
           FISH_TYPE, 
           IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(A.ID) AS FISH_COUNT, MAX(B.LENGTH) AS MAX_LENGTH, A.FISH_TYPE
FROM FISH_INFO AS A
JOIN FISH AS B
ON A.ID = B.ID
GROUP BY A.FISH_TYPE
HAVING AVG(B.LENGTH) >= 33
ORDER BY A.FISH_TYPE;
