-- 평균 길이가 33cm 이상인 물고기들을 종류별로 분류하여 정렬
-- 10cm 이하의 물고기들은 10cm 로 취급

WITH FISH AS (
    SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;